name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Oder "master", je nachdem wie dein Haupt-Branch heißt

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build # Stellt sicher, dass dein Vircadia/Babylon Projekt gebaut wird
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist" # Hier den Ordner angeben, den dein Build erzeugt (oft 'dist' oder 'build')

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4